#mysql container
db:
    restart: always
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: changeme
        #the values below should match the credentials used in prod.env
        MYSQL_USER: nbsap
        MYSQL_PASSWORD: nbsap
        MYSQL_DATABASE: nbsap

#per country container
ch:
    image:nbsap_web
    volumes:
        - ./countries_config/instance_ch/:/nbsap/instance
    ports:
        - "8000:7012"
    links:
        - db
    env_file:
        - ./env_files/ch.env
cy:
    image:nbsap_web
    volumes:
        - ./countries_config/instance_cy/:/nbsap/instance
    ports:
        - "8000:7003"
    links:
        - db
    env_file:
        - ./env_files/cy.env
de:
    image:nbsap_web
    volumes:
        - ./countries_config/instance_de/:/nbsap/instance
    ports:
        - "8000:7001"
    links:
        - db
    env_file:
        - ./env_files/de.env
dk:
    image:nbsap_web
    volumes:
        - ./countries_config/instance_dk/:/nbsap/instance
    ports:
        - "8000:7004"
    links:
        - db
    env_file:
        - ./env_files/dk.env
ee:
    image:nbsap_web
    volumes:
        - ./countries_config/instance_ee/:/nbsap/instance
    ports:
        - "8000:7005"
    links:
        - db
    env_file:
        - ./env_files/ee.env
hu:
    image:nbsap_web
    volumes:
        - ./countries_config/instance_hu/:/nbsap/instance
    ports:
        - "8000:7002"
    links:
        - db
    env_file:
        - ./env_files/hu.env
it:
    image:nbsap_web
    volumes:
        - ./countries_config/instance_it/:/nbsap/instance
    ports:
        - "8000:7006"
    links:
        - db
    env_file:
        - ./env_files/it.env
lu:
    image:nbsap_web
    volumes:
        - ./countries_config/instance_lu/:/nbsap/instance
    ports:
        - "8000:7007"
    links:
        - db
    env_file:
        - ./env_files/lu.env
lv:
    image:nbsap_web
    volumes:
        - ./countries_config/instance_lv/:/nbsap/instance
    ports:
        - "8000:7008"
    links:
        - db
    env_file:
        - ./env_files/lv.env
mt:
    image:nbsap_web
    volumes:
        - ./countries_config/instance_mt/:/nbsap/instance
    ports:
        - "8000:7009"
    links:
        - db
    env_file:
        - ./env_files/mt.env
sk:
    image:nbsap_web
    volumes:
        - ./countries_config/instance_sk/:/nbsap/instance
    ports:
        - "8000:7011"
    links:
        - db
    env_file:
        - ./env_files/sk.env
sl:
    image:nbsap_web
    volumes:
        - ./countries_config/instance_sl/:/nbsap/instance
    ports:
        - "8000:7010"
    links:
        - db
    env_file:
        - ./env_files/sl.env
