db:
    restart: always
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: changeme
        #the values below should match the credentials used in dev.env
        MYSQL_USER: nbsap
        MYSQL_PASSWORD: nbsap
        MYSQL_DATABASE: nbsap
web:
    build: ./nbsap
    command:
        bash -c "python instance/manage.py load_fixtures
                 python instance/manage.py migrate --run-syncdb &&
                 python instance/manage.py runserver 0.0.0.0:8000"
    volumes:
        - ./nbsap/:/nbsap
    ports:
        - "8000:8000"
    links:
        - db
    depends_on:
        - db

