db:
    restart: always
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: nbsap
        MYSQL_USER: nbsap
        MYSQL_PASSWORD: nbsap


dev:
    build: ./nbsap
    command:
        bash -c "python manage.py migrate --run-syncdb &&
                 python manage.py runserver 0.0.0.0:8000"
    env_file:
        - env/dev.env
    volumes:
        - ./nbsap/:/nbsap
    ports:
        - "8000:8000"
    links:
        - db
